# Generated by Django 2.2.13 on 2020-11-15 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Booking_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightticket',
            name='title',
        ),
        migrations.AddField(
            model_name='flightticket',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='flight_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='seat_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tickets',
            field=models.ManyToManyField(to='core.Flight_Booking_List'),
        ),
        migrations.DeleteModel(
            name='FlightBooked',
        ),
        migrations.AddField(
            model_name='flight_booking_list',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FlightTicket'),
        ),
        migrations.AddField(
            model_name='flight_booking_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
