# Generated by Django 2.2.13 on 2020-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flightticket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
