# Generated by Django 2.2.13 on 2020-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flightticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightticket',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
