# Generated by Django 2.2.13 on 2020-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201116_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking_list',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
