# Generated by Django 2.2.13 on 2020-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201118_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
