# Generated by Django 2.2.13 on 2020-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201118_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='duration_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='duration_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='number_first_class',
            field=models.IntegerField(default=6),
        ),
    ]
