# Generated by Django 2.2.13 on 2020-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201119_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightticket',
            old_name='number_first_class',
            new_name='first_class_seats',
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='number_seats_available',
            field=models.IntegerField(default=20),
        ),
    ]
