# Generated by Django 2.2.13 on 2020-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_destination_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='quote',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='things_to_do',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
