# Generated by Django 2.2.13 on 2020-11-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201120_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
