# Generated by Django 2.2.13 on 2020-11-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_destination_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='image',
            field=models.ImageField(blank=True, upload_to='airlines'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='quote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='things_to_do',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
