# Generated by Django 2.2.13 on 2020-11-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201120_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='map',
            field=models.ImageField(blank=True, upload_to='destination'),
        ),
        migrations.AddField(
            model_name='flight_booking_list',
            name='seats_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
