# Generated by Django 2.2.13 on 2020-11-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201123_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_booking_list',
            name='additional',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
