# Generated by Django 2.2.13 on 2020-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201124_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='discount_val',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
