# Generated by Django 2.2.13 on 2020-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_transactions_discount_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
    ]
