# Generated by Django 2.2.13 on 2020-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transactions_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='discounted',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='discount_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
