# Generated by Django 2.2.13 on 2020-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_last_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_booking_list',
            name='last_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Last_booked',
        ),
    ]
